package ro.mpp2024.rpcprotocol;

public enum RequestType {
    LOGIN,
    FIND_ACCOUNT,
    FIND_ALL_ARBITRI,
    FIND_PARTICIPANT,
    FIND_ALL_PARTICIPANTS,
    UPDATE_PARTICIPANT,
    ADD_REZULTAT,
    FIND_ALL_REZULTATE,
    UPDATE_REZULTAT,
    LOGOUT
}
