SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN
UPDATE Tipuri SET denumire='deadlock2' where descriere='descriere1'
WAITFOR DELAY '00:00:05'
UPDATE Carti SET titlu='DEADLOCK2' WHERE id=5
COMMIT TRAN