SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN
UPDATE Carti SET titlu='DEADLOCK' WHERE id=5
WAITFOR DELAY '00:00:05'
UPDATE Tipuri SET denumire='deadlock' where descriere='descriere1'
COMMIT TRAN