// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: triatlonProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from triatlonProtocol.proto</summary>
  public static partial class TriatlonProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for triatlonProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TriatlonProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ0cmlhdGxvblByb3RvY29sLnByb3RvEgVwcm90byJMCgdBcmJpdHJ1EgwK",
            "BG51bWUYASABKAkSEAoIdXNlcm5hbWUYAiABKAkSEAoIcGFzc3dvcmQYAyAB",
            "KAkSDwoHcHJvYmFpZBgEIAEoAyIrCgtQYXJ0aWNpcGFudBIMCgRudW1lGAEg",
            "ASgJEg4KBnB1bmN0ZRgCIAEoBSItCgVQcm9iYRIMCgRudW1lGAEgASgJEhYK",
            "DmlkX3BhcnRpY2lwYW50GAIgASgDIkQKCFJlenVsdGF0EhYKDnBhcnRpY2lw",
            "YW50X2lkGAEgASgDEhAKCHByb2JhX2lkGAIgASgDEg4KBnB1bmN0ZRgDIAEo",
            "BSKnAwoHUmVxdWVzdBIoCgR0eXBlGAEgASgOMhoucHJvdG8uUmVxdWVzdC5S",
            "ZXF1ZXN0VHlwZRIhCgdhcmJpdHJ1GAIgASgLMg4ucHJvdG8uQXJiaXRydUgA",
            "EikKC3BhcnRpY2lwYW50GAMgASgLMhIucHJvdG8uUGFydGljaXBhbnRIABId",
            "CgVwcm9iYRgEIAEoCzIMLnByb3RvLlByb2JhSAASIwoIcmV6dWx0YXQYBSAB",
            "KAsyDy5wcm90by5SZXp1bHRhdEgAItQBCgtSZXF1ZXN0VHlwZRIJCgVMT0dJ",
            "ThAAEhAKDEZJTkRfQUNDT1VOVBABEhQKEEZJTkRfQUxMX0FSQklUUkkQAhIU",
            "ChBGSU5EX1BBUlRJQ0lQQU5UEAMSGQoVRklORF9BTExfUEFSVElDSVBBTlRT",
            "EAQSFgoSVVBEQVRFX1BBUlRJQ0lQQU5UEAUSEAoMQUREX1JFWlVMVEFUEAYS",
            "FgoSRklORF9BTExfUkVaVUxUQVRFEAcSEwoPVVBEQVRFX1JFWlVMVEFUEAgS",
            "CgoGTE9HT1VUEAlCCQoHcmVxdWVzdCKEAgoIUmVzcG9uc2USKgoEdHlwZRgB",
            "IAEoDjIcLnByb3RvLlJlc3BvbnNlLlJlc3BvbnNlVHlwZRIfCgdhcmJpdHJp",
            "GAIgASgLMg4ucHJvdG8uQXJiaXRydRIoCgxwYXJ0aWNpcGFudGkYAyADKAsy",
            "Ei5wcm90by5QYXJ0aWNpcGFudBIbCgVwcm9iZRgEIAMoCzIMLnByb3RvLlBy",
            "b2JhEg4KBnB1bmN0ZRgFIAEoBRIPCgdtZXNzYWdlGAYgASgJIkMKDFJlc3Bv",
            "bnNlVHlwZRIGCgJPSxAAEhQKEFNVQ0NFU1NGVUxfTE9HSU4QARIJCgVFUlJP",
            "UhACEgoKBlVQREFURRADQi0KHHJvLm1wcDIwMjQucHJvdG9idWZmcHJvdG9j",
            "b2xCDVRyaWF0bG9uUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Arbitru), global::Proto.Arbitru.Parser, new[]{ "Nume", "Username", "Password", "Probaid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Participant), global::Proto.Participant.Parser, new[]{ "Nume", "Puncte" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Proba), global::Proto.Proba.Parser, new[]{ "Nume", "IdParticipant" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Rezultat), global::Proto.Rezultat.Parser, new[]{ "ParticipantId", "ProbaId", "Puncte" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Request), global::Proto.Request.Parser, new[]{ "Type", "Arbitru", "Participant", "Proba", "Rezultat" }, new[]{ "Request" }, new[]{ typeof(global::Proto.Request.Types.RequestType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Response), global::Proto.Response.Parser, new[]{ "Type", "Arbitri", "Participanti", "Probe", "Puncte", "Message" }, null, new[]{ typeof(global::Proto.Response.Types.ResponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Arbitru : pb::IMessage<Arbitru>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Arbitru> _parser = new pb::MessageParser<Arbitru>(() => new Arbitru());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Arbitru> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TriatlonProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Arbitru() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Arbitru(Arbitru other) : this() {
      nume_ = other.nume_;
      username_ = other.username_;
      password_ = other.password_;
      probaid_ = other.probaid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Arbitru Clone() {
      return new Arbitru(this);
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 1;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "probaid" field.</summary>
    public const int ProbaidFieldNumber = 4;
    private long probaid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Probaid {
      get { return probaid_; }
      set {
        probaid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Arbitru);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Arbitru other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nume != other.Nume) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (Probaid != other.Probaid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Probaid != 0L) hash ^= Probaid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (Probaid != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Probaid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (Probaid != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Probaid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Probaid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Probaid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Arbitru other) {
      if (other == null) {
        return;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Probaid != 0L) {
        Probaid = other.Probaid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 32: {
            Probaid = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
          case 32: {
            Probaid = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Participant : pb::IMessage<Participant>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Participant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TriatlonProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant(Participant other) : this() {
      nume_ = other.nume_;
      puncte_ = other.puncte_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant Clone() {
      return new Participant(this);
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 1;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "puncte" field.</summary>
    public const int PuncteFieldNumber = 2;
    private int puncte_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Puncte {
      get { return puncte_; }
      set {
        puncte_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Participant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Participant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nume != other.Nume) return false;
      if (Puncte != other.Puncte) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Puncte != 0) hash ^= Puncte.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (Puncte != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Puncte);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (Puncte != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Puncte);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Puncte != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Puncte);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Participant other) {
      if (other == null) {
        return;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Puncte != 0) {
        Puncte = other.Puncte;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 16: {
            Puncte = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 16: {
            Puncte = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Proba : pb::IMessage<Proba>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Proba> _parser = new pb::MessageParser<Proba>(() => new Proba());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Proba> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TriatlonProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba(Proba other) : this() {
      nume_ = other.nume_;
      idParticipant_ = other.idParticipant_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba Clone() {
      return new Proba(this);
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 1;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_participant" field.</summary>
    public const int IdParticipantFieldNumber = 2;
    private long idParticipant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdParticipant {
      get { return idParticipant_; }
      set {
        idParticipant_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Proba);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Proba other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nume != other.Nume) return false;
      if (IdParticipant != other.IdParticipant) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (IdParticipant != 0L) hash ^= IdParticipant.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (IdParticipant != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdParticipant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nume.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nume);
      }
      if (IdParticipant != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(IdParticipant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (IdParticipant != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdParticipant);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Proba other) {
      if (other == null) {
        return;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.IdParticipant != 0L) {
        IdParticipant = other.IdParticipant;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 16: {
            IdParticipant = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nume = input.ReadString();
            break;
          }
          case 16: {
            IdParticipant = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Rezultat : pb::IMessage<Rezultat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rezultat> _parser = new pb::MessageParser<Rezultat>(() => new Rezultat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Rezultat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TriatlonProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezultat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezultat(Rezultat other) : this() {
      participantId_ = other.participantId_;
      probaId_ = other.probaId_;
      puncte_ = other.puncte_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezultat Clone() {
      return new Rezultat(this);
    }

    /// <summary>Field number for the "participant_id" field.</summary>
    public const int ParticipantIdFieldNumber = 1;
    private long participantId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ParticipantId {
      get { return participantId_; }
      set {
        participantId_ = value;
      }
    }

    /// <summary>Field number for the "proba_id" field.</summary>
    public const int ProbaIdFieldNumber = 2;
    private long probaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ProbaId {
      get { return probaId_; }
      set {
        probaId_ = value;
      }
    }

    /// <summary>Field number for the "puncte" field.</summary>
    public const int PuncteFieldNumber = 3;
    private int puncte_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Puncte {
      get { return puncte_; }
      set {
        puncte_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Rezultat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Rezultat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ParticipantId != other.ParticipantId) return false;
      if (ProbaId != other.ProbaId) return false;
      if (Puncte != other.Puncte) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ParticipantId != 0L) hash ^= ParticipantId.GetHashCode();
      if (ProbaId != 0L) hash ^= ProbaId.GetHashCode();
      if (Puncte != 0) hash ^= Puncte.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ParticipantId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ParticipantId);
      }
      if (ProbaId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProbaId);
      }
      if (Puncte != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Puncte);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ParticipantId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ParticipantId);
      }
      if (ProbaId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProbaId);
      }
      if (Puncte != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Puncte);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ParticipantId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ParticipantId);
      }
      if (ProbaId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ProbaId);
      }
      if (Puncte != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Puncte);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Rezultat other) {
      if (other == null) {
        return;
      }
      if (other.ParticipantId != 0L) {
        ParticipantId = other.ParticipantId;
      }
      if (other.ProbaId != 0L) {
        ProbaId = other.ProbaId;
      }
      if (other.Puncte != 0) {
        Puncte = other.Puncte;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ParticipantId = input.ReadInt64();
            break;
          }
          case 16: {
            ProbaId = input.ReadInt64();
            break;
          }
          case 24: {
            Puncte = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ParticipantId = input.ReadInt64();
            break;
          }
          case 16: {
            ProbaId = input.ReadInt64();
            break;
          }
          case 24: {
            Puncte = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TriatlonProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.RequestCase) {
        case RequestOneofCase.Arbitru:
          Arbitru = other.Arbitru.Clone();
          break;
        case RequestOneofCase.Participant:
          Participant = other.Participant.Clone();
          break;
        case RequestOneofCase.Proba:
          Proba = other.Proba.Clone();
          break;
        case RequestOneofCase.Rezultat:
          Rezultat = other.Rezultat.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.Request.Types.RequestType type_ = global::Proto.Request.Types.RequestType.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Request.Types.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "arbitru" field.</summary>
    public const int ArbitruFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Arbitru Arbitru {
      get { return requestCase_ == RequestOneofCase.Arbitru ? (global::Proto.Arbitru) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.Arbitru;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Participant Participant {
      get { return requestCase_ == RequestOneofCase.Participant ? (global::Proto.Participant) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.Participant;
      }
    }

    /// <summary>Field number for the "proba" field.</summary>
    public const int ProbaFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Proba Proba {
      get { return requestCase_ == RequestOneofCase.Proba ? (global::Proto.Proba) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.Proba;
      }
    }

    /// <summary>Field number for the "rezultat" field.</summary>
    public const int RezultatFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Rezultat Rezultat {
      get { return requestCase_ == RequestOneofCase.Rezultat ? (global::Proto.Rezultat) request_ : null; }
      set {
        request_ = value;
        requestCase_ = value == null ? RequestOneofCase.None : RequestOneofCase.Rezultat;
      }
    }

    private object request_;
    /// <summary>Enum of possible cases for the "request" oneof.</summary>
    public enum RequestOneofCase {
      None = 0,
      Arbitru = 2,
      Participant = 3,
      Proba = 4,
      Rezultat = 5,
    }
    private RequestOneofCase requestCase_ = RequestOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestOneofCase RequestCase {
      get { return requestCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequest() {
      requestCase_ = RequestOneofCase.None;
      request_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Arbitru, other.Arbitru)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(Proba, other.Proba)) return false;
      if (!object.Equals(Rezultat, other.Rezultat)) return false;
      if (RequestCase != other.RequestCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.Request.Types.RequestType.Login) hash ^= Type.GetHashCode();
      if (requestCase_ == RequestOneofCase.Arbitru) hash ^= Arbitru.GetHashCode();
      if (requestCase_ == RequestOneofCase.Participant) hash ^= Participant.GetHashCode();
      if (requestCase_ == RequestOneofCase.Proba) hash ^= Proba.GetHashCode();
      if (requestCase_ == RequestOneofCase.Rezultat) hash ^= Rezultat.GetHashCode();
      hash ^= (int) requestCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (requestCase_ == RequestOneofCase.Arbitru) {
        output.WriteRawTag(18);
        output.WriteMessage(Arbitru);
      }
      if (requestCase_ == RequestOneofCase.Participant) {
        output.WriteRawTag(26);
        output.WriteMessage(Participant);
      }
      if (requestCase_ == RequestOneofCase.Proba) {
        output.WriteRawTag(34);
        output.WriteMessage(Proba);
      }
      if (requestCase_ == RequestOneofCase.Rezultat) {
        output.WriteRawTag(42);
        output.WriteMessage(Rezultat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (requestCase_ == RequestOneofCase.Arbitru) {
        output.WriteRawTag(18);
        output.WriteMessage(Arbitru);
      }
      if (requestCase_ == RequestOneofCase.Participant) {
        output.WriteRawTag(26);
        output.WriteMessage(Participant);
      }
      if (requestCase_ == RequestOneofCase.Proba) {
        output.WriteRawTag(34);
        output.WriteMessage(Proba);
      }
      if (requestCase_ == RequestOneofCase.Rezultat) {
        output.WriteRawTag(42);
        output.WriteMessage(Rezultat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (requestCase_ == RequestOneofCase.Arbitru) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Arbitru);
      }
      if (requestCase_ == RequestOneofCase.Participant) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (requestCase_ == RequestOneofCase.Proba) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Proba);
      }
      if (requestCase_ == RequestOneofCase.Rezultat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezultat);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.Request.Types.RequestType.Login) {
        Type = other.Type;
      }
      switch (other.RequestCase) {
        case RequestOneofCase.Arbitru:
          if (Arbitru == null) {
            Arbitru = new global::Proto.Arbitru();
          }
          Arbitru.MergeFrom(other.Arbitru);
          break;
        case RequestOneofCase.Participant:
          if (Participant == null) {
            Participant = new global::Proto.Participant();
          }
          Participant.MergeFrom(other.Participant);
          break;
        case RequestOneofCase.Proba:
          if (Proba == null) {
            Proba = new global::Proto.Proba();
          }
          Proba.MergeFrom(other.Proba);
          break;
        case RequestOneofCase.Rezultat:
          if (Rezultat == null) {
            Rezultat = new global::Proto.Rezultat();
          }
          Rezultat.MergeFrom(other.Rezultat);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Arbitru subBuilder = new global::Proto.Arbitru();
            if (requestCase_ == RequestOneofCase.Arbitru) {
              subBuilder.MergeFrom(Arbitru);
            }
            input.ReadMessage(subBuilder);
            Arbitru = subBuilder;
            break;
          }
          case 26: {
            global::Proto.Participant subBuilder = new global::Proto.Participant();
            if (requestCase_ == RequestOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 34: {
            global::Proto.Proba subBuilder = new global::Proto.Proba();
            if (requestCase_ == RequestOneofCase.Proba) {
              subBuilder.MergeFrom(Proba);
            }
            input.ReadMessage(subBuilder);
            Proba = subBuilder;
            break;
          }
          case 42: {
            global::Proto.Rezultat subBuilder = new global::Proto.Rezultat();
            if (requestCase_ == RequestOneofCase.Rezultat) {
              subBuilder.MergeFrom(Rezultat);
            }
            input.ReadMessage(subBuilder);
            Rezultat = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Arbitru subBuilder = new global::Proto.Arbitru();
            if (requestCase_ == RequestOneofCase.Arbitru) {
              subBuilder.MergeFrom(Arbitru);
            }
            input.ReadMessage(subBuilder);
            Arbitru = subBuilder;
            break;
          }
          case 26: {
            global::Proto.Participant subBuilder = new global::Proto.Participant();
            if (requestCase_ == RequestOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 34: {
            global::Proto.Proba subBuilder = new global::Proto.Proba();
            if (requestCase_ == RequestOneofCase.Proba) {
              subBuilder.MergeFrom(Proba);
            }
            input.ReadMessage(subBuilder);
            Proba = subBuilder;
            break;
          }
          case 42: {
            global::Proto.Rezultat subBuilder = new global::Proto.Rezultat();
            if (requestCase_ == RequestOneofCase.Rezultat) {
              subBuilder.MergeFrom(Rezultat);
            }
            input.ReadMessage(subBuilder);
            Rezultat = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("FIND_ACCOUNT")] FindAccount = 1,
        [pbr::OriginalName("FIND_ALL_ARBITRI")] FindAllArbitri = 2,
        [pbr::OriginalName("FIND_PARTICIPANT")] FindParticipant = 3,
        [pbr::OriginalName("FIND_ALL_PARTICIPANTS")] FindAllParticipants = 4,
        [pbr::OriginalName("UPDATE_PARTICIPANT")] UpdateParticipant = 5,
        [pbr::OriginalName("ADD_REZULTAT")] AddRezultat = 6,
        [pbr::OriginalName("FIND_ALL_REZULTATE")] FindAllRezultate = 7,
        [pbr::OriginalName("UPDATE_REZULTAT")] UpdateRezultat = 8,
        [pbr::OriginalName("LOGOUT")] Logout = 9,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TriatlonProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      arbitri_ = other.arbitri_ != null ? other.arbitri_.Clone() : null;
      participanti_ = other.participanti_.Clone();
      probe_ = other.probe_.Clone();
      puncte_ = other.puncte_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.Response.Types.ResponseType type_ = global::Proto.Response.Types.ResponseType.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Response.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "arbitri" field.</summary>
    public const int ArbitriFieldNumber = 2;
    private global::Proto.Arbitru arbitri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Arbitru Arbitri {
      get { return arbitri_; }
      set {
        arbitri_ = value;
      }
    }

    /// <summary>Field number for the "participanti" field.</summary>
    public const int ParticipantiFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Proto.Participant> _repeated_participanti_codec
        = pb::FieldCodec.ForMessage(26, global::Proto.Participant.Parser);
    private readonly pbc::RepeatedField<global::Proto.Participant> participanti_ = new pbc::RepeatedField<global::Proto.Participant>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.Participant> Participanti {
      get { return participanti_; }
    }

    /// <summary>Field number for the "probe" field.</summary>
    public const int ProbeFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Proto.Proba> _repeated_probe_codec
        = pb::FieldCodec.ForMessage(34, global::Proto.Proba.Parser);
    private readonly pbc::RepeatedField<global::Proto.Proba> probe_ = new pbc::RepeatedField<global::Proto.Proba>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.Proba> Probe {
      get { return probe_; }
    }

    /// <summary>Field number for the "puncte" field.</summary>
    public const int PuncteFieldNumber = 5;
    private int puncte_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Puncte {
      get { return puncte_; }
      set {
        puncte_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 6;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Arbitri, other.Arbitri)) return false;
      if(!participanti_.Equals(other.participanti_)) return false;
      if(!probe_.Equals(other.probe_)) return false;
      if (Puncte != other.Puncte) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.Response.Types.ResponseType.Ok) hash ^= Type.GetHashCode();
      if (arbitri_ != null) hash ^= Arbitri.GetHashCode();
      hash ^= participanti_.GetHashCode();
      hash ^= probe_.GetHashCode();
      if (Puncte != 0) hash ^= Puncte.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (arbitri_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Arbitri);
      }
      participanti_.WriteTo(output, _repeated_participanti_codec);
      probe_.WriteTo(output, _repeated_probe_codec);
      if (Puncte != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Puncte);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (arbitri_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Arbitri);
      }
      participanti_.WriteTo(ref output, _repeated_participanti_codec);
      probe_.WriteTo(ref output, _repeated_probe_codec);
      if (Puncte != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Puncte);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.Response.Types.ResponseType.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (arbitri_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Arbitri);
      }
      size += participanti_.CalculateSize(_repeated_participanti_codec);
      size += probe_.CalculateSize(_repeated_probe_codec);
      if (Puncte != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Puncte);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.Response.Types.ResponseType.Ok) {
        Type = other.Type;
      }
      if (other.arbitri_ != null) {
        if (arbitri_ == null) {
          Arbitri = new global::Proto.Arbitru();
        }
        Arbitri.MergeFrom(other.Arbitri);
      }
      participanti_.Add(other.participanti_);
      probe_.Add(other.probe_);
      if (other.Puncte != 0) {
        Puncte = other.Puncte;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            if (arbitri_ == null) {
              Arbitri = new global::Proto.Arbitru();
            }
            input.ReadMessage(Arbitri);
            break;
          }
          case 26: {
            participanti_.AddEntriesFrom(input, _repeated_participanti_codec);
            break;
          }
          case 34: {
            probe_.AddEntriesFrom(input, _repeated_probe_codec);
            break;
          }
          case 40: {
            Puncte = input.ReadInt32();
            break;
          }
          case 50: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            if (arbitri_ == null) {
              Arbitri = new global::Proto.Arbitru();
            }
            input.ReadMessage(Arbitri);
            break;
          }
          case 26: {
            participanti_.AddEntriesFrom(ref input, _repeated_participanti_codec);
            break;
          }
          case 34: {
            probe_.AddEntriesFrom(ref input, _repeated_probe_codec);
            break;
          }
          case 40: {
            Puncte = input.ReadInt32();
            break;
          }
          case 50: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("SUCCESSFUL_LOGIN")] SuccessfulLogin = 1,
        [pbr::OriginalName("ERROR")] Error = 2,
        [pbr::OriginalName("UPDATE")] Update = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
